import os
print(dir(os))
print(os.getcwd())
#os.chdir("C://")
print(os.getcwd())
h=open("mylog.txt")
print(os.listdir("C://"))
#os.mkdir("this")
#os.makedirs("this/that")
#os.rename("mylog.txt","mylogss.txt")
print(os.environ.get('path'))
print(os.path.join("c://","mylog.txt"))
os.path.exits("path")
os.rename("ooo.txt", "oooo.txt")